'use client'

import { useCallback, useEffect, useRef, useState } from 'react'
import { getSupabaseClient } from '@/lib/supabase/client'
import { PortalButton } from '@/components/ui/PortalButton'

/**
 * The expanded "Promote your talk" panel: a confirmed speaker's generated
 * speaker kit — share images, ready-to-post text variants with copy buttons,
 * their personal tracking link, and a download-everything zip.
 *
 * Data comes from /api/speaker-promo-kit (edit_token capability auth); the
 * kit itself is generated by the event-speakers module's workers, so this
 * component polls while status is requested/generating.
 */

interface PromoTextOption {
  key: string
  label: string
  body: string
}

interface PromoKit {
  status: 'requested' | 'generating' | 'ready' | 'failed'
  tracking_url?: string | null
  promo_text?: { options: PromoTextOption[]; mention_note?: string } | null
  promo_text_status?: string
  cards?: Array<{ format: string; storage_path: string; width: number; height: number }>
  zip_storage_path?: string | null
  deck_storage_path?: string | null
  generated_at?: string | null
}

interface Props {
  editToken: string
  /** Link to the speaker's own edit form — photo/name/role changes rebuild the kit. */
  editHref?: string
  primaryColor: string
  theme: {
    panelText: string
    panelTextMuted: string
  }
  /** Called on the first copy/download so the checklist can mark the task done. */
  onShared: () => void
}

const CARD_LABELS: Record<string, string> = {
  square: 'Feed post',
  story: 'Story',
  landscape: 'Link preview',
}

const POLL_INTERVAL_MS = 10_000
const MAX_POLLS = 60

export function SpeakerPromoKit({ editToken, editHref, primaryColor, theme, onShared }: Props) {
  const [kit, setKit] = useState<PromoKit | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [copiedKey, setCopiedKey] = useState<string | null>(null)
  const pollCount = useRef(0)
  const sharedRef = useRef(false)

  const publicUrl = useCallback(
    (path: string, version?: string | null) => {
      const supabase = getSupabaseClient()
      const base = supabase.storage.from('media').getPublicUrl(path).data.publicUrl
      // Kit artifacts are re-uploaded at stable paths on regenerate —
      // version-bust so browsers never serve a stale kit.
      return version ? `${base}?v=${encodeURIComponent(version)}` : base
    },
    [],
  )

  useEffect(() => {
    let cancelled = false
    let timer: ReturnType<typeof setTimeout> | null = null

    const fetchKit = async () => {
      try {
        const res = await fetch(`/api/speaker-promo-kit?token=${encodeURIComponent(editToken)}`)
        const data = await res.json()
        if (cancelled) return
        if (!res.ok || !data.success) {
          setError(data.error || 'Failed to load your speaker kit')
          return
        }
        setError(null)
        setKit(data)
        if ((data.status === 'requested' || data.status === 'generating') && pollCount.current < MAX_POLLS) {
          pollCount.current++
          timer = setTimeout(fetchKit, POLL_INTERVAL_MS)
        }
      } catch {
        if (!cancelled) setError('Failed to load your speaker kit')
      }
    }

    fetchKit()
    return () => {
      cancelled = true
      if (timer) clearTimeout(timer)
    }
  }, [editToken])

  const markShared = useCallback(() => {
    if (sharedRef.current) return
    sharedRef.current = true
    onShared()
  }, [onShared])

  const copyText = useCallback(
    async (key: string, text: string) => {
      try {
        await navigator.clipboard.writeText(text)
        setCopiedKey(key)
        setTimeout(() => setCopiedKey((k) => (k === key ? null : k)), 2000)
        markShared()
      } catch {
        // Clipboard can be unavailable (permissions); the text stays selectable.
      }
    },
    [markShared],
  )

  if (error) {
    return <p className="text-sm text-red-300">{error}</p>
  }

  if (!kit || kit.status === 'requested' || kit.status === 'generating') {
    return (
      <div className="flex items-center gap-2">
        <div
          className="loader w-4 h-4"
          style={{ '--primary-color': '#fff', '--secondary-color': primaryColor } as React.CSSProperties}
        />
        <span className={`text-sm ${theme.panelTextMuted}`}>
          We&apos;re preparing your speaker kit — share images, ready-to-post text, and your personal link.
          This can take a couple of minutes.
        </span>
      </div>
    )
  }

  if (kit.status === 'failed') {
    return (
      <p className="text-sm text-red-300">
        We couldn&apos;t generate your speaker kit. The organizers have been notified — please check back later.
      </p>
    )
  }

  const cards = kit.cards ?? []
  const options = kit.promo_text?.options ?? []

  return (
    <div className="space-y-4">
      {/* Share images */}
      {cards.length > 0 && (
        <div>
          <p className={`text-sm font-medium ${theme.panelText} mb-2`}>Share images</p>
          <div className="flex flex-wrap gap-3">
            {cards.map((card) => {
              const url = publicUrl(card.storage_path, kit.generated_at)
              return (
                <div key={card.format} className="w-28">
                  <a href={url} target="_blank" rel="noopener noreferrer" onClick={markShared}>
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img
                      src={url}
                      alt={`${CARD_LABELS[card.format] ?? card.format} speaker card`}
                      className="rounded-lg border border-white/20 w-full h-auto hover:opacity-90 transition-opacity"
                    />
                  </a>
                  <p className={`mt-1 text-xs text-center ${theme.panelTextMuted}`}>
                    {CARD_LABELS[card.format] ?? card.format}
                  </p>
                </div>
              )
            })}
          </div>
        </div>
      )}

      {/* Post text variants */}
      {options.length > 0 && (
        <div>
          <p className={`text-sm font-medium ${theme.panelText} mb-2`}>Ready-to-post text</p>
          <div className="space-y-2">
            {options.map((option) => (
              <details key={option.key} className="rounded-lg bg-white/10 border border-white/20">
                <summary
                  className={`cursor-pointer px-3 py-2 text-sm font-medium ${theme.panelText} select-none`}
                >
                  {option.label}
                </summary>
                <div className="px-3 pb-3 space-y-2">
                  <pre
                    className={`whitespace-pre-wrap font-sans text-sm ${theme.panelTextMuted} max-h-48 overflow-y-auto`}
                  >
                    {option.body}
                  </pre>
                  <PortalButton
                    variant="secondary"
                    size="small"
                    onClick={() => copyText(option.key, option.body)}
                  >
                    {copiedKey === option.key ? 'Copied!' : 'Copy post'}
                  </PortalButton>
                </div>
              </details>
            ))}
          </div>
          {kit.promo_text?.mention_note && (
            <p className={`mt-2 text-xs ${theme.panelTextMuted}`}>{kit.promo_text.mention_note}</p>
          )}
        </div>
      )}

      {/* Tracking link */}
      {kit.tracking_url && (
        <div>
          <p className={`text-sm font-medium ${theme.panelText} mb-1`}>Your personal link</p>
          <p className={`text-xs ${theme.panelTextMuted} mb-2`}>
            It&apos;s already in the posts above — registrations through it are credited to you.
          </p>
          <div className="flex items-center gap-2">
            <input
              type="text"
              value={kit.tracking_url}
              readOnly
              className="flex-1 px-3 py-2 text-sm rounded-lg bg-white/10 text-white border border-white/20 focus:outline-none select-all"
              onClick={(e) => (e.target as HTMLInputElement).select()}
            />
            <PortalButton
              variant="secondary"
              size="small"
              onClick={() => copyText('tracking-link', kit.tracking_url as string)}
              className="py-2"
            >
              {copiedKey === 'tracking-link' ? 'Copied!' : 'Copy'}
            </PortalButton>
          </div>
        </div>
      )}

      {/* Presentation template */}
      {kit.deck_storage_path && (
        <div>
          <p className={`text-sm font-medium ${theme.panelText} mb-1`}>Talk template</p>
          <p className={`text-xs ${theme.panelTextMuted} mb-2`}>
            Your slide deck starter with a branded title slide — build your talk in it. Opens in
            PowerPoint, or upload it to Google Drive and open with Google Slides.
          </p>
          <a href={publicUrl(kit.deck_storage_path, kit.generated_at)} download onClick={markShared}>
            <PortalButton variant="secondary" size="small">
              Download slide template (.pptx)
            </PortalButton>
          </a>
        </div>
      )}

      {/* Download everything */}
      {kit.zip_storage_path && (
        <div>
          <a href={publicUrl(kit.zip_storage_path, kit.generated_at)} download="speaker-kit.zip" onClick={markShared}>
            <PortalButton variant="primary" primaryColor={primaryColor} size="small">
              Download speaker kit (.zip)
            </PortalButton>
          </a>
        </div>
      )}

      {/* Your photo and details are printed onto the cards and the deck, so
          make the rebuild path obvious rather than leaving a stale kit. */}
      {editHref && (
        <p className={`text-xs ${theme.panelTextMuted} pt-1`}>
          Changed your photo, name, role or company?{' '}
          <a href={editHref} className="underline">
            Update your details
          </a>{' '}
          and we&apos;ll rebuild your kit automatically — it takes a couple of minutes.
        </p>
      )}
    </div>
  )
}
