// Copyright The Linux Foundation and each contributor to LFX.
// SPDX-License-Identifier: MIT

/**
 * Assembles the publishable @gatewaze/admin-embed package from the admin app's library build.
 *
 * The admin package itself is `private: true` and is the whole application; only the embed build
 * output is publishable. Rather than duplicate it, this copies `packages/admin/dist-embed/` into
 * `dist/` and writes the type declarations.
 *
 * The declarations are COPIED from the admin's own `src/embed/types.ts`, never hand-written — that
 * file is import-free and types-only precisely so it can be shipped verbatim, which keeps the
 * published contract from drifting away from the one the embed actually implements.
 */
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(here, '..');
const adminRoot = resolve(pkgRoot, '../admin');
const source = resolve(adminRoot, 'dist-embed');
const dist = resolve(pkgRoot, 'dist');

if (!existsSync(source)) {
  console.error(`[admin-embed] ${source} does not exist — run the admin embed build first:\n` + `  pnpm --filter @gatewaze/admin exec vite build -c vite.embed.config.ts`);
  process.exit(1);
}

// Always from clean: a stale chunk left behind by a previous build would be published alongside
// the current one, and the entry's hashed imports make that invisible until something 404s.
rmSync(dist, { recursive: true, force: true });
mkdirSync(dist, { recursive: true });
// Vite copies the admin app's whole `public/` tree into the library output — ~26MB of flags,
// logos and illustrations that is 72% of the package and reachable by nothing. Two reasons to
// drop it: no compiled chunk or CSS rule references `images/` (every url() in admin.css is a
// data: URI), and more fundamentally a browser cannot fetch a static file out of an npm package
// anyway — the host serves its own assets. Narrowing `publicDir` for the embed build upstream
// would remove the need for this filter.
cpSync(source, dist, {
  recursive: true,
  filter: (src) => !/[/\\]images([/\\]|$)/.test(src.slice(source.length)),
});

const types = readFileSync(resolve(adminRoot, 'src/embed/types.ts'), 'utf8');
writeFileSync(
  resolve(dist, 'index.d.ts'),
  [
    '// Generated by scripts/build.mjs — do not edit.',
    "// Copied verbatim from packages/admin/src/embed/types.ts, plus the entry's own exports.",
    '',
    types.trimEnd(),
    '',
    '/** Mounts the admin module set into `el`. Never throws; failures report through ctx.onFatal. */',
    'export declare function mount(el: HTMLElement, ctx: GwHostContext): GwEmbedHandle;',
    '',
    '/** Embed build version, logged by the host at mount so a support ticket can pin the build. */',
    'export declare const version: string;',
    '',
  ].join('\n')
);

console.log(`[admin-embed] assembled ${dist} from ${source}`);
