import { serve } from 'https://deno.land/std@0.177.0/http/server.ts';

// Auto-generated — do not edit manually.
// Regenerated by deployEdgeFunctions when module edge functions change.
//
// All functions use dynamic imports with error boundaries so that a broken
// function cannot crash the router or take down other functions.

const functions: Record<string, (req: Request) => Response | Promise<Response>> = {};
const loadErrors: Record<string, string> = {};

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, PUT, PATCH, DELETE, OPTIONS',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

// Load all functions with error boundaries
await (async () => {
  try { functions['admin-add-first'] = (await import('../admin-add-first/index.ts')).default; } catch (e) { loadErrors['admin-add-first'] = e?.message ?? String(e); }
  try { functions['admin-nl-query'] = (await import('../admin-nl-query/index.ts')).default; } catch (e) { loadErrors['admin-nl-query'] = e?.message ?? String(e); }
  try { functions['admin-send-magic-link'] = (await import('../admin-send-magic-link/index.ts')).default; } catch (e) { loadErrors['admin-send-magic-link'] = e?.message ?? String(e); }
  try { functions['calendars-api'] = (await import('../calendars-api/index.ts')).default; } catch (e) { loadErrors['calendars-api'] = e?.message ?? String(e); }
  try { functions['calendars-discover'] = (await import('../calendars-discover/index.ts')).default; } catch (e) { loadErrors['calendars-discover'] = e?.message ?? String(e); }
  try { functions['calendars-process-csv'] = (await import('../calendars-process-csv/index.ts')).default; } catch (e) { loadErrors['calendars-process-csv'] = e?.message ?? String(e); }
  try { functions['email-batch-send'] = (await import('../email-batch-send/index.ts')).default; } catch (e) { loadErrors['email-batch-send'] = e?.message ?? String(e); }
  try { functions['email-generate-encoded'] = (await import('../email-generate-encoded/index.ts')).default; } catch (e) { loadErrors['email-generate-encoded'] = e?.message ?? String(e); }
  try { functions['email-inbound-parse'] = (await import('../email-inbound-parse/index.ts')).default; } catch (e) { loadErrors['email-inbound-parse'] = e?.message ?? String(e); }
  try { functions['email-retry-send'] = (await import('../email-retry-send/index.ts')).default; } catch (e) { loadErrors['email-retry-send'] = e?.message ?? String(e); }
  try { functions['email-send'] = (await import('../email-send/index.ts')).default; } catch (e) { loadErrors['email-send'] = e?.message ?? String(e); }
  try { functions['email-send-push'] = (await import('../email-send-push/index.ts')).default; } catch (e) { loadErrors['email-send-push'] = e?.message ?? String(e); }
  try { functions['email-send-reminders'] = (await import('../email-send-reminders/index.ts')).default; } catch (e) { loadErrors['email-send-reminders'] = e?.message ?? String(e); }
  try { functions['email-sendgrid-webhook'] = (await import('../email-sendgrid-webhook/index.ts')).default; } catch (e) { loadErrors['email-sendgrid-webhook'] = e?.message ?? String(e); }
  try { functions['email-webhook'] = (await import('../email-webhook/index.ts')).default; } catch (e) { loadErrors['email-webhook'] = e?.message ?? String(e); }
  try { functions['events'] = (await import('../events/index.ts')).default; } catch (e) { loadErrors['events'] = e?.message ?? String(e); }
  try { functions['events-generate-matches'] = (await import('../events-generate-matches/index.ts')).default; } catch (e) { loadErrors['events-generate-matches'] = e?.message ?? String(e); }
  try { functions['events-registration'] = (await import('../events-registration/index.ts')).default; } catch (e) { loadErrors['events-registration'] = e?.message ?? String(e); }
  try { functions['events-search'] = (await import('../events-search/index.ts')).default; } catch (e) { loadErrors['events-search'] = e?.message ?? String(e); }
  try { functions['events-send-match-emails'] = (await import('../events-send-match-emails/index.ts')).default; } catch (e) { loadErrors['events-send-match-emails'] = e?.message ?? String(e); }
  try { functions['events-speaker-confirm'] = (await import('../events-speaker-confirm/index.ts')).default; } catch (e) { loadErrors['events-speaker-confirm'] = e?.message ?? String(e); }
  try { functions['events-speaker-submission'] = (await import('../events-speaker-submission/index.ts')).default; } catch (e) { loadErrors['events-speaker-submission'] = e?.message ?? String(e); }
  try { functions['events-speaker-submissions'] = (await import('../events-speaker-submissions/index.ts')).default; } catch (e) { loadErrors['events-speaker-submissions'] = e?.message ?? String(e); }
  try { functions['events-speaker-tracking-link'] = (await import('../events-speaker-tracking-link/index.ts')).default; } catch (e) { loadErrors['events-speaker-tracking-link'] = e?.message ?? String(e); }
  try { functions['events-speaker-update'] = (await import('../events-speaker-update/index.ts')).default; } catch (e) { loadErrors['events-speaker-update'] = e?.message ?? String(e); }
  try { functions['events-speaker-update-notify'] = (await import('../events-speaker-update-notify/index.ts')).default; } catch (e) { loadErrors['events-speaker-update-notify'] = e?.message ?? String(e); }
  try { functions['health-check'] = (await import('../health-check/index.ts')).default; } catch (e) { loadErrors['health-check'] = e?.message ?? String(e); }
  try { functions['integrations-luma-issue-discount'] = (await import('../integrations-luma-issue-discount/index.ts')).default; } catch (e) { loadErrors['integrations-luma-issue-discount'] = e?.message ?? String(e); }
  try { functions['integrations-luma-process-csv'] = (await import('../integrations-luma-process-csv/index.ts')).default; } catch (e) { loadErrors['integrations-luma-process-csv'] = e?.message ?? String(e); }
  try { functions['integrations-luma-process-registration'] = (await import('../integrations-luma-process-registration/index.ts')).default; } catch (e) { loadErrors['integrations-luma-process-registration'] = e?.message ?? String(e); }
  try { functions['integrations-luma-webhook'] = (await import('../integrations-luma-webhook/index.ts')).default; } catch (e) { loadErrors['integrations-luma-webhook'] = e?.message ?? String(e); }
  try { functions['integrations-track-offer'] = (await import('../integrations-track-offer/index.ts')).default; } catch (e) { loadErrors['integrations-track-offer'] = e?.message ?? String(e); }
  try { functions['media-combine-chunks'] = (await import('../media-combine-chunks/index.ts')).default; } catch (e) { loadErrors['media-combine-chunks'] = e?.message ?? String(e); }
  try { functions['media-get-youtube-upload-url'] = (await import('../media-get-youtube-upload-url/index.ts')).default; } catch (e) { loadErrors['media-get-youtube-upload-url'] = e?.message ?? String(e); }
  try { functions['media-process-image'] = (await import('../media-process-image/index.ts')).default; } catch (e) { loadErrors['media-process-image'] = e?.message ?? String(e); }
  try { functions['media-process-youtube-uploads'] = (await import('../media-process-youtube-uploads/index.ts')).default; } catch (e) { loadErrors['media-process-youtube-uploads'] = e?.message ?? String(e); }
  try { functions['media-process-zip'] = (await import('../media-process-zip/index.ts')).default; } catch (e) { loadErrors['media-process-zip'] = e?.message ?? String(e); }
  try { functions['media-upload-youtube'] = (await import('../media-upload-youtube/index.ts')).default; } catch (e) { loadErrors['media-upload-youtube'] = e?.message ?? String(e); }
  try { functions['newsletter-gdoc-import'] = (await import('../newsletter-gdoc-import/index.ts')).default; } catch (e) { loadErrors['newsletter-gdoc-import'] = e?.message ?? String(e); }
  try { functions['newsletter-send'] = (await import('../newsletter-send/index.ts')).default; } catch (e) { loadErrors['newsletter-send'] = e?.message ?? String(e); }
  try { functions['newsletter-unsubscribe'] = (await import('../newsletter-unsubscribe/index.ts')).default; } catch (e) { loadErrors['newsletter-unsubscribe'] = e?.message ?? String(e); }
  try { functions['people-classify-job-titles'] = (await import('../people-classify-job-titles/index.ts')).default; } catch (e) { loadErrors['people-classify-job-titles'] = e?.message ?? String(e); }
  try { functions['people-enrichment'] = (await import('../people-enrichment/index.ts')).default; } catch (e) { loadErrors['people-enrichment'] = e?.message ?? String(e); }
  try { functions['people-normalize-location'] = (await import('../people-normalize-location/index.ts')).default; } catch (e) { loadErrors['people-normalize-location'] = e?.message ?? String(e); }
  try { functions['people-profile-update'] = (await import('../people-profile-update/index.ts')).default; } catch (e) { loadErrors['people-profile-update'] = e?.message ?? String(e); }
  try { functions['people-signup'] = (await import('../people-signup/index.ts')).default; } catch (e) { loadErrors['people-signup'] = e?.message ?? String(e); }
  try { functions['people-track-attribute'] = (await import('../people-track-attribute/index.ts')).default; } catch (e) { loadErrors['people-track-attribute'] = e?.message ?? String(e); }
  try { functions['people-track-subscription'] = (await import('../people-track-subscription/index.ts')).default; } catch (e) { loadErrors['people-track-subscription'] = e?.message ?? String(e); }
  try { functions['people-validate-linkedin'] = (await import('../people-validate-linkedin/index.ts')).default; } catch (e) { loadErrors['people-validate-linkedin'] = e?.message ?? String(e); }
  try { functions['platform-generate-download-token'] = (await import('../platform-generate-download-token/index.ts')).default; } catch (e) { loadErrors['platform-generate-download-token'] = e?.message ?? String(e); }
  try { functions['platform-generate-embeddings'] = (await import('../platform-generate-embeddings/index.ts')).default; } catch (e) { loadErrors['platform-generate-embeddings'] = e?.message ?? String(e); }
  try { functions['platform-setup'] = (await import('../platform-setup/index.ts')).default; } catch (e) { loadErrors['platform-setup'] = e?.message ?? String(e); }
})();

const loaded = Object.keys(functions).length;
const failed = Object.keys(loadErrors).length;
console.log(`[platform-main] Loaded ${loaded} functions, ${failed} failed`);
if (failed > 0) console.log('[platform-main] Failed:', Object.entries(loadErrors).map(([k,v]) => `${k}: ${v}`).join(', '));

serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  const url = new URL(req.url);
  const pathSegments = url.pathname.split('/').filter(Boolean);

  let functionName: string | undefined;
  if (pathSegments.length >= 3 && pathSegments[0] === 'functions' && pathSegments[1] === 'v1') {
    functionName = pathSegments[2];
  } else if (pathSegments.length >= 1) {
    functionName = pathSegments[0];
  }

  const handler = functionName ? functions[functionName] : undefined;

  if (!handler) {
    const loadError = functionName ? loadErrors[functionName] : undefined;
    if (loadError) {
      return new Response(
        JSON.stringify({ error: `Function "${functionName}" failed to load: ${loadError}` }),
        { status: 503, headers: { ...corsHeaders, 'Content-Type': 'application/json' } },
      );
    }
    return new Response(
      JSON.stringify({ error: `Function not found: ${functionName ?? 'unknown'}` }),
      { status: 404, headers: { ...corsHeaders, 'Content-Type': 'application/json' } },
    );
  }

  try {
    return await handler(req);
  } catch (error) {
    console.error(`[platform-main] Error in "${functionName}":`, error);
    return new Response(
      JSON.stringify({ error: error?.message ?? `Internal error in ${functionName}` }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } },
    );
  }
});
