import { serve } from 'https://deno.land/std@0.177.0/http/server.ts';

// Auto-generated — do not edit manually.
// Regenerated by deployEdgeFunctions when module edge functions change.
import adminAddFirst from '../admin-add-first/index.ts';
import adminSendMagicLink from '../admin-send-magic-link/index.ts';
import emailSend from '../email-send/index.ts';
import emailSendReminders from '../email-send-reminders/index.ts';
import emailSendgridWebhook from '../email-sendgrid-webhook/index.ts';
import peopleProfileUpdate from '../people-profile-update/index.ts';
import peopleSignup from '../people-signup/index.ts';
import platformGenerateDownloadToken from '../platform-generate-download-token/index.ts';
import platformSetup from '../platform-setup/index.ts';

const functions: Record<string, (req: Request) => Response | Promise<Response>> = {
  'admin-add-first': adminAddFirst,
  'admin-send-magic-link': adminSendMagicLink,
  'email-send': emailSend,
  'email-send-reminders': emailSendReminders,
  'email-sendgrid-webhook': emailSendgridWebhook,
  'people-profile-update': peopleProfileUpdate,
  'people-signup': peopleSignup,
  'platform-generate-download-token': platformGenerateDownloadToken,
  'platform-setup': platformSetup,
};

// Module edge functions loaded dynamically (gracefully skipped if not yet deployed)
await (async () => {
  try { functions['calendars-api'] = (await import('../calendars-api/index.ts')).default; } catch { /* module not deployed yet */ }
  try { functions['calendars-discover'] = (await import('../calendars-discover/index.ts')).default; } catch { /* module not deployed yet */ }
  try { functions['calendars-process-csv'] = (await import('../calendars-process-csv/index.ts')).default; } catch { /* module not deployed yet */ }
  try { functions['events-speaker-confirm'] = (await import('../events-speaker-confirm/index.ts')).default; } catch { /* module not deployed yet */ }
  try { functions['events-speaker-submission'] = (await import('../events-speaker-submission/index.ts')).default; } catch { /* module not deployed yet */ }
  try { functions['events-speaker-submissions'] = (await import('../events-speaker-submissions/index.ts')).default; } catch { /* module not deployed yet */ }
  try { functions['events-speaker-tracking-link'] = (await import('../events-speaker-tracking-link/index.ts')).default; } catch { /* module not deployed yet */ }
  try { functions['events-speaker-update'] = (await import('../events-speaker-update/index.ts')).default; } catch { /* module not deployed yet */ }
  try { functions['events-speaker-update-notify'] = (await import('../events-speaker-update-notify/index.ts')).default; } catch { /* module not deployed yet */ }
  try { functions['integrations-track-offer'] = (await import('../integrations-track-offer/index.ts')).default; } catch { /* module not deployed yet */ }
})();

serve(async (req: Request) => {
  const url = new URL(req.url);
  const pathSegments = url.pathname.split('/').filter(Boolean);

  // Route: /functionName or /functions/v1/functionName
  let functionName: string | undefined;

  if (pathSegments.length >= 3 && pathSegments[0] === 'functions' && pathSegments[1] === 'v1') {
    functionName = pathSegments[2];
  } else if (pathSegments.length >= 1) {
    functionName = pathSegments[0];
  }

  const handler = functionName ? functions[functionName] : undefined;

  if (!handler) {
    return new Response(
      JSON.stringify({ error: `Function not found: ${functionName ?? 'unknown'}` }),
      { status: 404, headers: { 'Content-Type': 'application/json' } },
    );
  }

  try {
    return await handler(req);
  } catch (error) {
    console.error(`Error invoking function ${functionName}:`, error);
    return new Response(
      JSON.stringify({ error: `Internal error in function ${functionName}` }),
      { status: 500, headers: { 'Content-Type': 'application/json' } },
    );
  }
});
